### PR TITLE
#117 Add basic Parquet support

### PR DESCRIPTION
**Pull request by jerolba**
Following other integrations format patters, support saving and loading Parquet files.

## Supported types

Main Java types are mapped to Parquet data types

| Java Type | Parquet Type |
|---|---|
| boolean/Boolean | boolean |
| byte/Byte | int32(8, false) |
| short/Short | int32(16, false) |
| int/Integer | int32|
| long/Long | int64 |
| float/Float | float |
| double/Double | double |
| String | binary (STRING) |
| Enum | binary (ENUM) (*) |
| UUID | fixed_len_byte_array(16) (UUID) |
| LocalDate | int32 (DATE) |
| LocalTime | int32 (TIME(unit=MILLIS\|MICROS))<br>int64 (TIME(unit=NANOS)) |
| LocalDateTime | int64 (TIMESTAMP(MILLIS\|MICROS\|NANOS, isAdjustedToUTC= false)) |
| Instant | int64 (TIMESTAMP(MILLIS\|MICROS\|NANOS, isAdjustedToUTC= true)) |
| BigDecimal | int32 (DECIMAL)  (precision <=9)  <br> int64 (DECIMAL)  (precision <=18) <br> binary (DECIMAL) <br> fixed_len_byte_array (DECIMAL) |

**Nested records and collections are not supported. Just plain table values are supported.**

(*) if DataFrame column is a Java Enum, it's serialized to Parquet with enum type, but if a Parquet file has column defined as parquet Enum type, the DataFrame column will be an String

## Saver configuration
In Parquet format you need to configure "resolution" at some column types,
* Date and Time resolution: for seconds, select to use milliseconds, microseconds or nanoseconds. Default value  is microseconds. 
* BigDecimal scale and precision: globally to the file configure which scale and precision to use. Because it's difficult to configure a default value, I decided to throw an exception if a BigDecimal column is present in the DataFrame,

Parquet writer can tune a lot of parameters. By default I have not exposed those parameters except one: compression codec, where you can select between multiple libraries: snappy, gzip, lz4, etc.
It's useful to select one compression algorithm

## Hadoop Dependencies

I've excluded all possible Hadoop transitive dependencies, leaving strictly necessary to compile and execute an application.
If users of the library requires it, they can just add required Hadoop dependencies in their project.

### CODE REVIEW

**Comment by andrus** [comment]
@jerolba : At a quick glance, this looks very nice and thorough and can serve as a solid foundation for Parquet in DFLib! 

Since this is a sizable and non-trivial contribution, may I ask you to fill and sign a CLA at https://www.objectstyle.com/f/cla/icla.pdf and email it to the address mentioned in the PDF? It is modeled after Apache and Spring CLAs to ensure we can continue to distribute DFLib as a whole under the Apache license.

**Comment by jerolba** [comment]
@andrus now I don't have access to a printer to sign manually it. 
Does ObjectStyle have a digital signature service like docusign.com? 
I don't know when I will get access to a printer, and until then the PR will be blocked.

**Comment by andrus** [comment]
Yeah, no need to print it. It should be enough if you add blocks of text to the PDF, and "sign" it in the bottom with your name (another block of text). 

But if it is more convenient, I can upload it to PandaDoc (the service that we use for esignatures elsewhere), but I will need your email to send the signature request (which you can also send to cla at objectstyle.com). 

Whichever way you prefer should work.

**Comment by andrus** [comment]
Going forward, we should modernize our CLA process with smth like https://cla-assistant.io/ I guess :)

**Comment by jerolba** [comment]
We can try it if you want, I've no issue on be the tester :)

**Comment by andrus** [comment]
The "modernization" piece is for later. I also don't want to block this PR. So can we do one of the other options: either a PDF "signature" or Pandadocs (in the latter case, I will need your email).

**Comment by andrus** [comment]
We have the CLA on file now. Thanks!

I applied the following change to the PR, and tried to run it in Jupyter. Unfortunately, getting some dependency exceptions in the loader. Looks like we need to undo some exclusions?

image


```
diff --git a/dflib-jupyter/pom.xml b/dflib-jupyter/pom.xml
index 29fb8a4f..c88875ec 100644
--- a/dflib-jupyter/pom.xml
+++ b/dflib-jupyter/pom.xml
@@ -36,6 +36,11 @@
             <artifactId>dflib-excel</artifactId>
             <version>${project.version}</version>
         </dependency>
+        <dependency>
+            <groupId>org.dflib</groupId>
+            <artifactId>dflib-parquet</artifactId>
+            <version>${project.version}</version>
+        </dependency>
         <dependency>
             <groupId>org.dflib</groupId>
             <artifactId>dflib-jdbc</artifactId>
diff --git a/dflib-parquet/pom.xml b/dflib-parquet/pom.xml
index 7aad9c38..eb85c50f 100644
--- a/dflib-parquet/pom.xml
+++ b/dflib-parquet/pom.xml
@@ -59,7 +59,6 @@
         <dependency>
             <groupId>org.apache.hadoop</groupId>
             <artifactId>hadoop-client</artifactId>
-            <scope>provided</scope>
             <exclusions>
                <exclusion>
                        <groupId>org.apache.hadoop</groupId>
```

**Comment by jerolba** [comment]
I don't know why it is not failing in test execution time. The woodstox dependency is also removed for tests...

Reading the file, before processing it, we need to get the schema, and I'm using an utility class `ParquetFileReader`, Internally instantiates a `HadoopParquetConfiguration` (which requires a lot of dependencies) if no configuration is provided.

Providing a custom (and empty) `PlainParquetConfiguration` will avoid the codepath that instantiates the `HadoopParquetConfiguration`.

We execute this code just to get and parse the schema from parquet metadata. The real file parse is done later.

I expect that this will solve the issue.

**Comment by andrus** [comment]
With the latest version, I am getting the same error, but coming from a different place:

```
java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
	at org.apache.parquet.conf.HadoopParquetConfiguration.<init>(HadoopParquetConfiguration.java:39)
	at org.apache.parquet.conf.HadoopParquetConfiguration.<init>(HadoopParquetConfiguration.java:35)
	at org.apache.parquet.hadoop.ParquetReader$Builder.<init>(ParquetReader.java:236)
	at org.dflib.parquet.read.DataframeParquetReaderBuilder.<init>(DataframeParquetReaderBuilder.java:10)
	at org.dflib.parquet.ParquetLoader.load(ParquetLoader.java:48)
	at org.dflib.parquet.ParquetLoader.load(ParquetLoader.java:28)
	at org.dflib.parquet.ParquetLoader.load(ParquetLoader.java:32)
	at .(#17:1)
```

**Comment by jerolba** [comment]
I think that I got it! Comparing with [Carpet configuration](https://github.com/jerolba/parquet-carpet/blob/master/carpet-record/build.gradle#L38) I realize that I forgot to include hadoop-common dependency

**Comment by andrus** [comment]
Unfortunately, getting the same exact error. I will try to convert this random Parquet file that I found on the internet to a unit test (probably in the next day or two).

**Comment by jerolba** [comment]
Can you give me the URL of the file to reproduce the error?

**Comment by andrus** [comment]
It is the first file here https://www.tablab.app/datasets/sample/parquet

**Comment by jerolba** [comment]
I can not reproduce the error loading that file.

After doing a mvn install, I ve created an empty project with this pom.xml:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.jerolba</groupId>
  <artifactId>dflib-client</artifactId>
  <version>0.0.1-SNAPSHOT</version>
   <properties>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.source>17</maven.compiler.source>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.dflib</groupId>
            <artifactId>dflib-parquet</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.dflib</groupId>
            <artifactId>dflib</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>  
</project>
```

I can read the file with this code:

```java
import org.dflib.DataFrame;
import org.dflib.parquet.Parquet;

public class DflibClient {

    public static void main(String[] args) {
        DataFrame df = Parquet.loader().load("/tmp/MT cars.parquet");
        System.out.println(df);
    }
}
```

How can I reproduce your setup to test it?

**Comment by andrus** [comment]
BTW, your code works for me just fine. Let me try to inspect the classpath differences with Jupyter

**Comment by andrus** [comment]
After trying it with Java , jshell, and Jupyter, I think the issue is likely in the Jupyter Java "kernel" classpath resolving mechanism. I can't put a finger on it yet, but let's ignore this error for now. I am going to continue testing the PR in thos other environments.

**Comment by andrus** [comment]
Just merged the PR. Thanks a lot for the contribution. Now planning to add more options (like picking specific columns when loading data, etc.). But it is already very usable (especially, after we fix the Jupyter kernel issue 😀 )

**Comment by jerolba** [comment]
FYI: for column filtering, reading the file, you will need to modify the class `DataframeReadSupport` passing requested columns as custom configuration, and then filtering from schema those columns in method init:

```java
MessageType schema = initContext.getFileSchema();
MessageType projection = projectRequestedColums(schema, requestdColums);
```

In Carpet you have an example of this logic here: https://github.com/jerolba/parquet-carpet/blob/master/carpet-record/src/main/java/com/jerolba/carpet/CarpetParquetReader.java#L154

With parquet projections you can save reading and decoding of parquet columns.

Doing these type of changes mention me in the PR or email me if you need help.

**Comment by andrus** [comment]
@jerolba : I figured out how to do column selection. This is committed already. But I wonder how do I specify encodings (https://parquet.apache.org/docs/file-format/data-pages/encodings/) ? I noticed that the `.parquet` file above re-encoded via DFLib is 1.5x larger than the original. Both are "snappy" compressed, but the former is `S _ R` and the latter is `S RR_`. `ParquetWriter.Builder` doesn't seem to have such options.

**Comment by jerolba** [comment]
AFAIK, you can not select the encoding, it's applied automatically by the code given each column type.

You can select the Parquet Format version to use, that changes some internal data structures, and uses some advanced encondings (https://stackoverflow.com/a/77682818).
To change the version call to `withWriterVersion` with `WriterVersion.PARQUET_2_0)` creating the writer builder.

In my experience it's risky to configure PARQUET_2_0 by default because some Python tooling doesn't support it and will fail reading your file if they don't configure latest version of their libraries (I have suffered in my work)

Are you saving the information in the same order? it can affect the dictionary having different distribution of values.

What is  `S _ R` and `S RR_`?

**Comment by andrus** [comment]
`S _ R` and `S RR_` are the encoding codes shown by `parquet meta xyz.parquet`. This may be red herring, but this is the main difference I noticed between the original file (encoded by DuckDB it appears) and the one produced by DFLib. There are also some subtle schema differences:

Produced by DFLib, 4238 bytes:
```
optional binary model (STRING);
optional double mpg;
optional int32 cyl;
optional double disp;
optional int32 hp;
optional double drat;
optional double wt;
optional double qsec;
optional int32 vs;
optional int32 am;
optional int32 gear;
optional int32 carb;
```

the original file, 2932 bytes:
```
optional binary model (STRING);
optional double mpg;
optional int32 cyl (INTEGER(32,true));
optional double disp;
optional int32 hp (INTEGER(32,true));
optional double drat;
optional double wt;
optional double qsec;
optional int32 vs (INTEGER(32,true));
optional int32 am (INTEGER(32,true));
optional int32 gear (INTEGER(32,true));
optional int32 carb (INTEGER(32,true));
```

**Pull request merged**
